version: '2.29.2'

services:
  postgres:
    build:
      dockerfile: Dockerfile-postgres
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - db:/var/lib/postgresql/data


  file-service:
    build:
      dockerfile: Dockerfile-service
    image: 'file-service-app:latest'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      JWT_SECRET_ACCESS: 'qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w=='
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: 'true'

volumes:
  db:
    driver: local